Hospital/Controllers/HospitalController.cs
using Hospital.Models;
using Hospital.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Omu.AwesomeMvc;
using Omu.SampleData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Controllers.HospitalController
{
    public class HospitalController : Controller
    {
        private IRepository repository;
        public HospitalController(IRepository _repository)
        {
            repository = _repository;
        }

        [Authorize]
        public IActionResult MainPage(string massege)
        {
            return View(massege);
        }

        [Authorize]
        public IActionResult ShowAllPatient(string iin, string surname, int page = 1, SortState sortState = SortState.NAME_PATIENT_ASC )
        {
            int pageSize = 3;
            IQueryable<Patient> patients = repository.GetAllPatients;

            //Фильтрация
            if (iin != null)
            {
                patients = patients.Where(p => p.IIN == iin);
            }
            if (!String.IsNullOrEmpty(surname))
            {
                patients = patients.Where(p => p.Surname.ToLower().Contains(surname.ToLower()));
            }
            //сортировка
            patients = repository.SortPatients(sortState, patients);

            //пагинация

            var count = patients.Count();
            var items = patients.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            //формируем модель представления
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = new PageViewModel(count, page, pageSize),
                SortViewModel = new SortViewModel(sortState),
                FilterViewModel = new FilterViewModel(iin, surname),
                Patients = items,
                Streets = repository.GetAllStreet
            };
            return View(viewModel);
        }
        public IActionResult Details(int? id)
        {
            if (id != null)
            {
                Patient patient = repository.GetAllPatients.FirstOrDefault(p => p.Id == id);
                if (patient != null)
                {
                    return View(patient);
                }
            }
            return NotFound();
        }
        [HttpGet]
        public IActionResult ChoosePatient()
        {
            ViewBag.iin = 0;
            ViewBag.name = string.Empty;

            return View();
        }

        [HttpPost]
        public IActionResult ChoosePatient(int iin, string name)
        {
            Patient _patient;
            if (iin != 0)
            {
                _patient = repository.GetPatientByIIN(iin.ToString());
                return RedirectToAction("CartPatient", "Hospital", _patient);

            }
            if (name != null)
            {
                _patient = repository.GetPatientByFIO(name);
                return RedirectToAction("CartPatient", "Hospital", _patient);
            }
            return View();
        }
        [Authorize]
        public IActionResult EditPatient(int? id)
        {
            if (id != null)
            {
                Patient patient = repository.GetPatientByID(id);
                if (patient != null)
                {
                    return PartialView("EditPatient", new PatientWithStreets { Patient = patient, Streets = repository.GetAllStreet});
                }
            }
            return NotFound();
        }
        [Authorize]
        [HttpPost]
        public IActionResult EditPatient(Patient patient)
        {
            if (ModelState.IsValid)
            {
                repository.SavePatient(patient);
                TempData["message"] = $"Пациент: {patient.Surname} {patient.Name} был изменен";
                return RedirectToAction("ShowAllPatient");
            }
            else
            {
                return View(patient);
            }
        }
        [Authorize]
        [HttpGet]
        public IActionResult AddPatient()
        {
            return PartialView("AddPatient", new PatientWithStreets() { Streets = repository.GetAllStreet});/*для него по умолчанию не определяется мастер-страница.*/
        }
        [Authorize]
        [HttpPost]
        public IActionResult AddPatient(Patient patient)
        {
            if (ModelState.IsValid)
            {
                repository.AddPatient(patient);
                TempData["message"] = $"Пациент: {patient.Surname} {patient.Name} был добавлен";
                return RedirectToAction("MainPage", "Hospital");
            }
            else
            {
                return PartialView("AddPatient");
            }
        }
        [Authorize]
        [HttpGet]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Patient patient = repository.GetPatientByID(id);
                if (patient != null)
                {
                    return View(patient);
                }
            }
            return NotFound();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                Patient patient = repository.GetPatientByID(id);
                if (patient != null)
                {
                    repository.DeletePatient(patient);
                    TempData["message"] = $"Пациент: {patient.Surname} {patient.Name} был удален";
                    return RedirectToAction("MainPage");
                }
            }
            return NotFound();
        }
    }
}

Hospital/Controllers/VisitHistoryController.cs
using Hospital.Models;
using Hospital.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Controllers
{
    public class VisitHistoryController : Controller
    {
        private readonly IRepository repository;
        public int countItemOnOnePage = 4;
        public VisitHistoryController(IRepository _repository)
        {
            repository = _repository;
        }
        [Authorize]
        public ViewResult ShowAllVisitHistoryByIdPatient(int idPatient, int numberPage = 1, SortState sortState = SortState.DATE_ASC)
        {
            //сортировка
            IQueryable<VisitHistory> visitHistories = repository.SortVisitRecords(sortState, repository.GetAllVisitHistoriesByIdPatient(idPatient));

            //пагинация
            var items = visitHistories.Skip((numberPage - 1) * countItemOnOnePage).Take(countItemOnOnePage);

            //формируем модель представления
            VisitsHistoryPatientViewModel viewModel = new VisitsHistoryPatientViewModel
            {
                VisitHistories = items,
                PagingInfo = new PageInfoVisitHistoryViewModel { CurrentPage = numberPage, ItemsPerPage = countItemOnOnePage, TotalItems = repository.GetAllVisitHistoriesByIdPatient(idPatient).Count() },
                IdPatient = idPatient,
                SortVisitRecords = new SortVisitRecordsViewModel(sortState)
            };
            return View(viewModel);

        }
        [Authorize]
        public IActionResult AddVisitHistoryById(int idPatient)
        {
            ViewBag.idPatient = idPatient;
            ViewBag.Doctors = repository.GetAllDoctors;
            ViewBag.Diagnoses = repository.GetAllDiagnoses;
            VisitRecordfForEditViewModel viewModel = new VisitRecordfForEditViewModel() { VisitRecord = new VisitHistory(),  DiagnozLists = repository.GetAllDiagnoses, Doctors = repository.GetAllDoctors, IdPatient = idPatient };
            return View(viewModel);
        }
        [Authorize]
        [HttpPost]
        public IActionResult AddVisitHistoryById(VisitRecordfForEditViewModel newRecordInVisitHistory)
        {
            if (ModelState.IsValid)
            {
                repository.AddNewRecordInVisitHistory(newRecordInVisitHistory.VisitRecord);
                TempData["message"] = $"Новая запись о пациенте  добавлена";
                return RedirectToAction("MainPage", "Hospital");
            }
            else
            {
                //newRecordInVisitHistory = new VisitRecordfForEditViewModel() { VisitRecord = new VisitHistory(), DiagnozLists = repository.GetAllDiagnoses, Doctors = repository.GetAllDoctors, IdPatient = idPatient };
                return View(newRecordInVisitHistory);
            }
        }
        [Authorize]
        [HttpGet]
        [ActionName("Delete")]
        public IActionResult ConfirnDelete(int? id)
        {
            if (id != null)
            {
                VisitHistory visirRecord = repository.GetVisitRecordById(id);
                if (visirRecord != null)
                {
                    return View(visirRecord);
                }
            }
            return NotFound();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Delete(int?id)
        {
            repository.DeleteVisitRecord(id);
            TempData["message"] = $"Запись посещения была удалена";
            return RedirectToAction("MainPage", "Hospital");
        }
        [Authorize]
        public IActionResult EditVisitRecord(int? id)
        {
            if (id != null)
            {
                VisitHistory visitRecord = repository.GetVisitRecordById(id);
                if (visitRecord != null)
                {
                    VisitRecordfForEditViewModel viewModel = new VisitRecordfForEditViewModel(visitRecord, repository.GetAllDiagnoses, repository.GetAllDoctors, 0);                   
                    return View(viewModel);
                }
            }
            return NotFound();
        }
        [Authorize]
        [HttpPost]
        public IActionResult EditVisitRecord(VisitHistory visitRecord)
        {
            if (ModelState.IsValid)
            {
                repository.SaveVisitRecord(visitRecord);
                TempData["message"] = $"Запись под ID: {visitRecord.Id} дата: {visitRecord.Date} была изменена";
                return RedirectToAction("MainPage", "Hospital");
            }
            else
            {
                VisitRecordfForEditViewModel viewModel = new VisitRecordfForEditViewModel(visitRecord, repository.GetAllDiagnoses, repository.GetAllDoctors, 0);
                return View(viewModel);

            }
        }
    }
}

Hospital/Views/Hospital/AddPatient.cshtml
@model PatientWithStreets

    <div class="modal fade" id="modalExample">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title">Форма добавления клиента</h1>
                </div>

                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-10">
                            <h4>Заполните поля</h4>
                            <form action="AddPatient">
                                <div class="p-3 form-group">
                                    <label asp-for="Patient.IIN"></label>
                                    <input type="number" asp-for="Patient.IIN" class="form-control iin" />
                                    <span asp-validation-for="Patient.IIN" class="text-danger text-center"></span>
                                </div>
                                <div class="p-3 form-group">
                                    <label asp-for="Patient.Name"></label>
                                    <input asp-for="Patient.Name" type="text" class="form-control" />
                                    <span asp-validation-for="Patient.Name" class="text-danger text-center"></span>

                                </div>
                                <div class="p-3 form-group">
                                    <label asp-for="Patient.Surname"></label>
                                    <input asp-for="Patient.Surname" type="text" class="form-control" />
                                    <span asp-validation-for="Patient.Surname" class="text-danger text-center"></span>

                                </div>
                                <div class="p-3 form-group">
                                    <label asp-for="Patient.Patronymic"></label>
                                    <input asp-for="Patient.Patronymic" type="text" class="form-control" />
                                    <span asp-validation-for="Patient.Patronymic" class="text-danger text-center"></span>

                                </div>
                                <div class="p-3 form-group">
                                    <label asp-for="Patient.StreetId"></label>
                                    <select asp-for="Patient.StreetId" class="form-control  form-select ">
                                        <option selected disabled>Список улиц</option>
                                        @foreach (Street str in Model.Streets)
                                        {
                                            <option value=@str.Id>@str.Name</option>
                                        }
                                    </select>
                                    <span asp-validation-for="Patient.StreetId" class="text-danger text-center"></span>

                                </div>
                                <div class="p-3 form-group">
                                    <label asp-for="Patient.HouseNumber"></label>
                                    <input asp-for="Patient.HouseNumber" type="number" class="form-control" />
                                    <span asp-validation-for="Patient.HouseNumber" class="text-danger text-center"></span>

                                </div>
                                <div class="p-3 form-group">
                                    <label asp-for="Patient.AppartmentNumber"></label>
                                    <input asp-for="Patient.AppartmentNumber" type="text" class="form-control" />
                                    <span asp-validation-for="Patient.AppartmentNumber" class="text-danger text-center"></span>

                                </div>
                                <div class="p-3 form-group">
                                    <label asp-for="Patient.PhoneNumber"></label>
                                    <input asp-for="Patient.PhoneNumber" type="number" class="form-control" />
                                    <span asp-validation-for="Patient.PhoneNumber" class="text-danger text-center"></span>

                                </div>

                            </form>

                        </div>


                    </div>
                </div>
                <div class="modal-footer">
                        <button type="button" class="btn btn-primary " data-save="modal">Добавить</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                </div>
            </div>
        </div>
    </div>


Hospital/Views/Hospital/ChoosePatient.cshtml
@model Patient
@{
    int iin = 0;
}
<div class="text-center">
    <div class="d-sm-inline-flex ">
        <div>
            <input type="radio" name="typeSearch" id="searchIIN" style="visibility:visible" onclick="Do()" />
            <label for="searchIIN">Искать по ИИН</label>
            <form asp-controller="Hospital" asp-action="ChoosePatient"  method="post" id="formIIN">
                <div>
                    <label></label>
                    <input type="text" asp-for="@iin" />
                </div>
                <input type="submit" value="Искать" />
            </form>

        </div>
        <p>ИЛИ</p>
        <div>

            <input type="radio" name="typeSearch" id="searchFIO" onclick="s" />
            <label for="searchName">Искать по ФИО</label>
            <form asp-controller="Hospital" asp-action="ChoosePatient" method="post" id="formFIO">
                <div>
                    <label asp-for="Name"></label>
                    <input asp-for="Name" />
                </div>
                <input type="submit" />
            </form>

        </div>

    </div>


</div>

<script src="~/js/JavaScript.js"></script>



Hospital/Views/Hospital/Delete.cshtml
@model Patient
@{ 
    ViewBag.Title = "Удаление пациента";
}

<div class="border border-1 text-center">
    <h3 class="text-warning text-uppercase">Внимание! Вы собираетесь удалить следующего пациента: </h3>
    <dl class="list-group-horizontal-lg">
       <dt>ФИО</dt>
        <dd>
            @Html.DisplayFor(model => model.Surname)
            @Html.DisplayFor(model => model.Name)
            @Html.DisplayFor(model => model.Patronymic)
        </dd>
        <dt>ИИН</dt>
        <dd>@Html.DisplayFor(model => model.IIN)</dd>

    </dl>
    <div>
        <form asp-action="Delete" method="post" asp-route-id="@Model.Id">
            <div class="form-check">
                <input type="submit" class="btn btn-danger"  value="Удалить" />
                <a asp-action="MainPage" class="btn btn-primary" >Отмена</a>
            </div>
        </form>
    </div>
</div>

Hospital/Views/Hospital/Details.cshtml
@model Patient
@{ ViewBag.Title = "Подробности";}
<table border="1" class="table table-bordered table-primary table-hover">
    <thead>
        <tr>
            <th>ИИН</th>
            <th>ФИО</th>
            <th>Улица</th>
            <th>№ дома</th>
            <th>№ квартиры</th>
            <th>Номер телефона</th>

        </tr>
    </thead>
    <tbody>
       
        <tr>
            <td>@Model.IIN</td>
            <td>@Model.Surname  @Model.Name  @Model.Patronymic</td>
            <td>@Model.Street.Name</td>
            <td>@Model.HouseNumber</td>
            <td>@Model.AppartmentNumber</td>
            <td>@Model.PhoneNumber</td>
        </tr>
    </tbody>
</table>

Hospital/Views/Hospital/EditPatient.cshtml
@model PatientWithStreets
<div class="modal fade" id="modalEdit">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title">Редактирование формы пациента</h1>
            </div>

            <div class="modal-body">
                <div class="col-10">
                    <h3 class="text-center">
                        Редактировать сведения о пациенте
                    </h3>
                    <form action="EditPatient" >
                        <div hidden="hidden">
                            <input asp-for="Patient.Id" value="@Model.Patient.Id" hidden="hidden" />
                        </div>
                        <div>
                            <label asp-for="Patient.IIN"></label>
                            <input type="number" asp-for="Patient.IIN" class="form-control" />
                            <span asp-validation-for="Patient.IIN" class="text-danger text-center"></span>
                        </div>
                        <div>
                            <label asp-for="Patient.Name"></label>
                            <input asp-for="Patient.Name" type="text" class="form-control" />
                            <span asp-validation-for="Patient.Name" class="text-danger text-center"></span>

                        </div>
                        <div>
                            <label asp-for="Patient.Surname"></label>
                            <input asp-for="Patient.Surname" type="text" class="form-control" />
                            <span asp-validation-for="Patient.Surname" class="text-danger text-center"></span>

                        </div>
                        <div>
                            <label asp-for="Patient.Patronymic"></label>
                            <input asp-for="Patient.Patronymic" type="text" class="form-control" />
                            <span asp-validation-for="Patient.Patronymic" class="text-danger text-center"></span>

                        </div>
                        <div>
                            <label asp-for="Patient.StreetId"></label>
                            <select asp-for="Patient.StreetId" class="form-control">
                                @foreach (Street str in Model.Streets)
                                {
                                    <option value=@str.Id>@str.Name</option>
                                }
                            </select>
                            <span asp-validation-for="Patient.StreetId" class="text-danger text-center"></span>

                        </div>
                        <div>
                            <label asp-for="Patient.HouseNumber"></label>
                            <input asp-for="Patient.HouseNumber" type="text" class="form-control" />
                            <span asp-validation-for="Patient.HouseNumber" class="text-danger text-center"></span>

                        </div>
                        <div>
                            <label asp-for="Patient.AppartmentNumber"></label>
                            <input asp-for="Patient.AppartmentNumber" type="text" class="form-control" />
                            <span asp-validation-for="Patient.AppartmentNumber" class="text-danger text-center"></span>

                        </div>
                        <div>
                            <label asp-for="Patient.PhoneNumber"></label>
                            <input asp-for="Patient.PhoneNumber" type="number" class="form-control" />
                            <span asp-validation-for="Patient.PhoneNumber" class="text-danger text-center"></span>

                        </div>

                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-edit="modal">Редактировать</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                </div>
            </div>
        </div>
    </div>
</div>

Hospital/Views/Hospital/MainPage.cshtml
@model string
<h2 class="text-center welcome"><i class="fas fa-comment-medical text-success"></i> Добро пожаловать </h2>

Hospital/Views/Hospital/ShowAllPatient.cshtml
@model IndexViewModel
@{
    ViewBag.Title = "Все пациенты";
    int iterNumber = 0;
}
<div class="row p-3">
    <div class="col-lg-3">
        <h3>Отфильтровать по: </h3>
        <form method="get">
            <div class="form-inline">
                <label>Фамилии: </label>
                <input name="surname" value="@Model.FilterViewModel.SelectedSurname" class="form-control" />
                <label>ИИН: </label>
                <input name="iin" value="@Model.FilterViewModel.SelectedIIN" class="form-control" />

                <input type="submit" value="Поиск" class="btn btn-outline-dark mt-2" />
                <input type="button" value="Очистить" class="btn btn-warning btn-clear mt-2">
            </div>
        </form>
    </div>
    <div class="col-lg-9">
        <h3 class="text-center">Список пациентов</h3>
        <table class="table table-bordered table-primary table-hover col-lg-9">
            <tr>
                <th>№</th>
                <th>
                    <a asp-action="ShowAllPatient" asp-route-sortState="@(Model.SortViewModel.FIOSort)"
                       asp-route-surname="@(Model.FilterViewModel.SelectedSurname)"
                       asp-route-iin="@(Model.FilterViewModel.SelectedIIN)">ФИО</a>
                </th>
                <th>
                    <a asp-action="ShowAllPatient" asp-route-sortState="@(Model.SortViewModel.IINSort)"
                       asp-route-surname="@(Model.FilterViewModel.SelectedSurname)"
                       asp-route-iin="@(Model.FilterViewModel.SelectedIIN)">ИИН</a>
                </th>
                <th>
                    Действия
                </th>
            </tr>
            @foreach (Patient p in Model.Patients)
            {
                <tr>
                    <td>@(++iterNumber)</td>
                    <td>@p.Surname @p.Name @p.Patronymic</td>
                    <td>@p.IIN</td>
                    <td>
                        <form asp-action="Delete" method="get">
                            <button type="button" class="btn btn-warning" data-toggle="ajax-modal" data-target="#modalEdit" data-id=@p.Id data-url="@Url.Action("EditPatient", "Hospital")">Редактировать</button>
                            <a asp-action="ShowAllVisitHistoryByIdPatient" asp-controller="VisitHistory" asp-route-idpatient="@p.Id" class="btn btn-info">История посещений</a>
                            <input type="hidden" name="id" value="@p.Id" />
                            <button type="submit" class="btn btn-danger">Удалить</button>

                        </form>
                    </td>
                </tr>
            }
        </table>
        <div class="align-self-center">
            @if (Model.PageViewModel.HasPreviousPage)
            {
                <a asp-action="ShowAllPatient" asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
                   asp-route-fio="@(Model.FilterViewModel.SelectedSurname)"
                   asp-route-iin="@(Model.FilterViewModel.SelectedIIN)"
                   asp-route-sortState="@(Model.SortViewModel.Current)"
                   class="btn btn-outline-dark">Назад</a>
            }
            @if (Model.PageViewModel.HasNextPage)
            {
                <a asp-action="ShowAllPatient" asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
                   asp-route-fio="@(Model.FilterViewModel.SelectedSurname)"
                   asp-route-iin="@(Model.FilterViewModel.SelectedIIN)"
                   asp-route-sortState="@(Model.SortViewModel.Current)"
                   class="btn btn-outline-dark">Вперед</a>
            }
        </div>
        <div id="PlaceHolderHere"></div>

        <div id="add_patient" class="text-center">
            <div class="myDiv">
                <button type="button" class="btn btn-primary" data-toggle="ajax-modal" data-target="#modalExample" data-url="@Url.Action("AddPatient", "Hospital")">Добавить пациента</button>
            </div>
        </div>
    </div>
</div>